### ISSUE TITLE
libproxy fails to compile with NetworkManager-1.0.6

### ISSUE THREAD

**Issue by tgurr** [libproxy/libproxy#2]
When building libproxy 0.4.11 and/or git master with the NetworkManager module enabled it fails to compile with NetworkManager 1.0.6:

```
In file included from /usr/x86_64-pc-linux-gnu/include/NetworkManager/NetworkManager.h:29:0,
                 from /var/tmp/paludis/build/net-libs-libproxy-0.4.11-r2/work/libproxy-0.4.11/libproxy/modules/network_networkmanager.cpp:26:
/usr/x86_64-pc-linux-gnu/include/NetworkManager/nm-version.h:24:18: fatal error: glib.h: No such file or directory
 #include <glib.h>
                  ^
compilation terminated.
make[2]: *** [libproxy/CMakeFiles/network_networkmanager.dir/modules/network_networkmanager.cpp.o] Error 1
make[1]: *** [libproxy/CMakeFiles/network_networkmanager.dir/all] Error 2
make: *** [all] Error 2
```

Later versions of NetworkManager >1.0.6 don't seem to include glib.h anymore:
http://cgit.freedesktop.org/NetworkManager/NetworkManager/commit/?id=7bf10a75db84655e65fe6216d248f7775c58ca23

I've no idea how to properly fix this, Gentoo however carries a patch to remove the NetworkManager build time dependency all together because it's causing circular dependency problems which are always a huge pain for downstream distribution maintainers.

The bug: https://bugs.gentoo.org/show_bug.cgi?id=467696
The patch: https://gitweb.gentoo.org/repo/gentoo.git/tree/net-libs/libproxy/files/libproxy-0.4.11-avoid-nm-build-dep.patch

With that patch applied libproxy also builds (and hopefully works) fine with NetworkManager-1.0.6 installed.

**Comment by DimStar77** [comment]
Thank you very much for your report.. I'll see to get a fix into libproxy for that.

as for the circular dependency: in openSUSE this is solved by splitting the build of libproxy in two parts: libproxy (the library and headers) and a 2nd build for all the modules. NM then only depends on the libproxy-devel (header and lib); the config modules are not needed for this...

**Comment by DimStar77** [comment]
>In file included from /usr/x86_64-pc-linux-gnu/include/NetworkManager/NetworkManager.h:29:0,
                 from /var/tmp/paludis/build/net-libs-libproxy-0.4.11-r2/work/libproxy-0.4.11/libproxy/modules/network_networkmanager.cpp:26:
>/usr/x86_64-pc-linux-gnu/include/NetworkManager/nm-version.h:24:18: fatal error: glib.h: No such file or directory
> #include <glib.h>

That actually means: NetworkManager includes glib.h;  (file /usr/x86_64-pc-linux-gnu/include/NetworkManager/nm-version.h belongs to NetworkManager)

libproxy does nothing wrong there: we 'require' the module NetworkManager by libproxy (we could query libnm-glib, that would hide the problem). The module 'NetworkManager' (as per pkg-config) does not depend  on glib (which I guess it should not), yet, NetworkManager.h includes glib.h... thus resulting in your issue.

This has since been fixed in NetworkManager devel tree:
http://cgit.freedesktop.org/NetworkManager/NetworkManager/commit/?h=nm-1-0&id=d0e367aeb7895b9fb39f2800d9ca9eab1f348a38

as a workaround for your build, you can inject $(pkg-config --cflags glib-2.0) into your CFLAGS to get this to build. 
As the bug is in NM, I will close this issue.

**Comment by tgurr** [comment]
Thanks for clarification. It's mainly a problem for souce-based distributions where it's rather uncommon to split upstream packages, however you can enable/disable options such as the NetworkManager module via the package manager but this involves additional user interaction to manually work around such circular depencies.
But at least on Exherbo we try to avoid shipping downstream patches or workarounds which are not upstreamable as much as possible, so I guess I'll rather apply the upstream commit you've posted to our NetworkManager package in the hope it won't cause any problem for other packages.
