### ISSUE TITLE
libproxy-0.4.13 fails to compile with NetworkManager-1.2.0

### ISSUE THREAD

**Issue by tgurr** [libproxy/libproxy#26]
`
[ 92%] Built target proxy
libproxy/CMakeFiles/network_networkmanager.dir/build.make:65: recipe for target 'libproxy/CMakeFiles/network_networkmanager.dir/modules/network_networkmanager.cpp.o' failed
make[2]: Leaving directory '/var/tmp/paludis/build/net-libs-libproxy-0.4.13/work/build'
CMakeFiles/Makefile2:1045: recipe for target 'libproxy/CMakeFiles/network_networkmanager.dir/all' failed
/var/tmp/paludis/build/net-libs-libproxy-0.4.13/work/libproxy-0.4.13/libproxy/modules/network_networkmanager.cpp:26:43: fatal error: NetworkManager/NetworkManager.h: No such file or directory
compilation terminated.
make[2]: *** [libproxy/CMakeFiles/network_networkmanager.dir/modules/network_networkmanager.cpp.o] Error 1
make[1]: *** [libproxy/CMakeFiles/network_networkmanager.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
`

While in previous NetworkManager versions the NetworkManager.h was located in:
`/usr/x86_64-pc-linux-gnu/include/NetworkManager/NetworkManager.h`
in recent versions (>=1.2.0) it is located in:
`/usr/x86_64-pc-linux-gnu/include/libnm/NetworkManager.h`

**Comment by DimStar77** [comment]
Thanks for the report - the latest version NM I tested was 1.1.93 - did they really move headers around at that time... tststs

I'll have a look at that shortly

**Comment by tgurr** [comment]
I'm afraid it still fails to compile for me with that commit applied, attached is my build.log
[libproxy-0.4.13_build.log.txt](https://github.com/libproxy/libproxy/files/244757/libproxy-0.4.13_build.log.txt)

**Comment by DimStar77** [comment]
from NetworkManager 1.2.0 libnm-util/Makefile.am:

```
libnm_util_include_HEADERS =            \
        $(top_builddir)/shared/nm-version-macros.h \
        NetworkManager.h                \
[...]
libnm_util_includedir=$(includedir)/NetworkManager

```

It seems as if your NetworkManager installation is broken. NetworkManager.h is still c orrectly installed to %{includedir}/NetworkManager/NetworkManager.h

**Comment by tgurr** [comment]
It's only there if you build NetworkManager 1.2.0 with the option --with-libnm-glib (build legacy libraries), however I don't think libproxy actually requires that (?).

**Comment by DimStar77** [comment]
Good catch ! We indeed do not rely on the legacy lib, just on the dbus interface - seems I have to rewrite the build system to query for libnm and fallback to NetworkManager if not found

**Comment by DimStar77** [comment]
quick shot:

`diff --git a/libproxy/cmake/modules/network_networkmanager.cmk b/libproxy/cmake/modules/network_networkmanager.cmk
index d9f9588..4399557 100644
--- a/libproxy/cmake/modules/network_networkmanager.cmk
+++ b/libproxy/cmake/modules/network_networkmanager.cmk
@@ -1,3 +1,6 @@
 if (NOT WIN32 AND NOT APPLE)
-  px_check_modules(NM NetworkManager dbus-1)
-endif()
\ No newline at end of file
+  px_check_modules(NM libnm dbus-1)
+  if (NOT NM_FOUND)
+    px_check_modules(NM NetworkManager dbus-1)
+  endif (NOT NM_FOUND)
+endif()
diff --git a/libproxy/modules/network_networkmanager.cpp b/libproxy/modules/network_networkmanager.cpp
index f55593c..ee68764 100644
--- a/libproxy/modules/network_networkmanager.cpp
+++ b/libproxy/modules/network_networkmanager.cpp
@@ -76,7 +76,7 @@ public:
                        // If a message is the right type and value,
                        // we'll reset the network
                        if (dbus_message_get_args(msg, NULL, DBUS_TYPE_UINT32, &state, DBUS_TYPE_INVALID))
-                               if (state == NM_STATE_CONNECTED)
+                               if (state == NM_STATE_CONNECTED_GLOBAL)
`

**Comment by DimStar77** [comment]
quick shot (not fully tested):

```
diff --git a/libproxy/cmake/modules/network_networkmanager.cmk b/libproxy/cmake/modules/network_networkmanager.cmk
index d9f9588..4399557 100644
--- a/libproxy/cmake/modules/network_networkmanager.cmk
+++ b/libproxy/cmake/modules/network_networkmanager.cmk
@@ -1,3 +1,6 @@
 if (NOT WIN32 AND NOT APPLE)
-  px_check_modules(NM NetworkManager dbus-1)
-endif()
\ No newline at end of file
+  px_check_modules(NM libnm dbus-1)
+  if (NOT NM_FOUND)
+    px_check_modules(NM NetworkManager dbus-1)
+  endif (NOT NM_FOUND)
+endif()
diff --git a/libproxy/modules/network_networkmanager.cpp b/libproxy/modules/network_networkmanager.cpp
index f55593c..ee68764 100644
--- a/libproxy/modules/network_networkmanager.cpp
+++ b/libproxy/modules/network_networkmanager.cpp
@@ -76,7 +76,7 @@ public:
                        // If a message is the right type and value,
                        // we'll reset the network
                        if (dbus_message_get_args(msg, NULL, DBUS_TYPE_UINT32, &state, DBUS_TYPE_INVALID))
-                               if (state == NM_STATE_CONNECTED)
+                               if (state == NM_STATE_CONNECTED_GLOBAL)

```

**Comment by DimStar77** [comment]
+                               if (state == NM_STATE_CONNECTED_GLOBAL)

in the past we used NM_STATE_CONNECTED which was just defined as
  ./NetworkManager/NetworkManager.h:#define NM_STATE_CONNECTED NM_STATE_CONNECTED_GLOBAL

Will have to check how long ago this was defined as such - we should not raise the bar for NM too high

**Comment by tgurr** [comment]
With cdad87b6e7d2ebe3489ff151f90c1188ef65f903 and the above diff applied libproxy-0.4.13 compiles fine for me against NetworkManager 1.2.0 (build with --without-libnm-glib) now.

**Comment by DimStar77** [comment]
Thanks for the quick test from your end - so at least we are on the right track here...
